# PVE服务器配置
proxmox:
  host: "192.168.7.2"
  user: "root@pam"
  password: "your_password"
  node: "pve"
  verify_ssl: false

# 存储配置
storage:
  name: "local-lvm"
  type: "lvmthin"

# 虚拟机配置列表
vms:
  - id: 100
    cloud_init: false  # 明确标记不使用 cloud-init
    name: "OpenWrt"
    memory: 1024
    cores: 2
    sockets: 1
    ostype: "l26"
    scsihw: "virtio-scsi-single"
    net0: "virtio,bridge=vmbr0,firewall=1"
    scsi0: "local-lvm:0,import-from=/var/lib/vz/template/iso/openwrt.img"
    boot_order:  # 新增启动顺序配置
      - scsi0    # 首先从硬盘启动
      - net0     # 最后是网络启动
    tags: "network,router"

  - id: 101
    cloud_init: false  # 明确标记不使用 cloud-init
    name: "Ikuai"
    memory: 4096
    cores: 4
    sockets: 1
    ostype: "l26"
    scsihw: "virtio-scsi-single"
    net0: "virtio,bridge=vmbr0,firewall=1"
    scsi0: "local-lvm:8,format=raw"
    ide2: "local:/var/lib/vz/template/iso/ikuai.iso,media=cdrom"
    boot_order:  # 新增启动顺序配置
      - ide2
      - scsi0    # 首先从硬盘启动
      - net0     # 最后是网络启动
    tags: "network,router"
